[workspace]
authors = ["Tobias Hunger <tobias.hunger@gmail.com>"]
channels = ["conda-forge"]
name = "octoconda"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]
add-repo = { cmd = "python scripts/add_repo.py" }
rebalance-repos = { cmd = "python scripts/rebalance_repos.py" }
build-one = { cmd = "bash scripts/build_one.sh" }

[dependencies]
7zip = "*"
actionlint = "*"
zizmor = "*"
rattler-build = "*"
python = ">=3.12"
requests = "*"
beautifulsoup4 = "*"
